READMEbutbetter.md
nanuwo/cube-sim-cpp pull request #1
Opened 2024-12-12 14:24 UTC by Annahile

horse moment
but better

2024-12-12 14:25 UTC, Annahile commented
PLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASEPLEASE

2024-12-12 14:25 UTC, Annahile commented
I'll let you see a real live horse instead of just one online :)))))))))

2024-12-13 14:37 UTC, nanuwo commented
Prepare for unforeseen consequences

2024-12-13 14:41 UTC, nanowuu requested changes

2024-12-13 14:41 UTC, nanowuu commented on README.md
> +print("I am a horse annd welcome to my ashow!!!")
this is utter garbage

2024-12-13 14:41 UTC, nanuwo commented on README.md
> +print("I am a horse annd welcome to my ashow!!!")
improper language

2024-12-13 14:42 UTC, nanuwo requested changes
review

2024-12-13 14:42 UTC, nanuwo commented
> review 

shut up

2024-12-13 14:42 UTC, closed without merging